[project]
name = "oracelion"
version = "0.1.0"
description = "Advanced AI Transcriber"
authors = [
    {name = "Rohit Ranjan",email = "ranjan.rohit2207@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
